# Generated by Django 3.1.4 on 2021-03-25 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qtech_search_engine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('user_sid', models.CharField(max_length=100)),
                ('keyword', models.ManyToManyField(to='qtech_search_engine.KeywordDescriptionModel')),
            ],
        ),
    ]
